import { useMemo, useState } from 'react'
import { ArrowLeftRight, ExternalLink, Scale, ShieldCheck, Vote } from 'lucide-react'
import { groundTruth } from './data/v2'
import { afdRealityCheck, behaviourEvidence, bundestagData, fiscalEvidence, partyHousehold180k, partyHousehold40k, zewSource } from './data/reality'

const money = (value: number) => `${value >= 0 ? '+' : '−'}${Math.abs(value).toLocaleString('de-DE')} €`

export default function RealityLab() {
  const [income, setIncome] = useState<40 | 180>(40)
  const rows = income === 40 ? partyHousehold40k : partyHousehold180k
  const max = useMemo(() => Math.max(...rows.map((row) => Math.abs(row.euro))), [rows])

  return <main className="min-h-screen bg-bg text-ink">
    <header className="border-b border-border bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-4 sm:px-6"><a href="./" className="font-black">FairEint</a><span className="rounded-full bg-ink px-2 py-1 text-[10px] font-black text-white">Reality Lab</span><a href="?workshop=1" className="ml-auto text-xs font-bold text-ink-muted">Workshop-Modus</a></div></header>

    <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><div className="max-w-4xl"><div className="text-xs font-black uppercase tracking-[0.18em] text-gold">Veröffentlichte Mikrosimulation statt Bauchgefühl</div><h1 className="mt-3 text-5xl font-black leading-[0.98] tracking-[-0.04em]">Wer profitiert wirklich von einem Parteiprogramm?</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-ink-soft">FairEint übernimmt hier keine eigene politische Bewertung. Wir zeigen veröffentlichte Ergebnisse aus ZEW-EviSTA auf Basis des SOEP, daneben die Parteibehauptung und die Grenzen des Modells.</p></div>

      <section className="mt-10 rounded-[2rem] border border-border bg-white p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-widest text-gold">ZEW Beispielhaushalt</div><h2 className="mt-2 text-2xl font-black">Alleinverdiener-Ehepaar · 2 Kinder</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-ink-muted">Veränderung des verfügbaren Jahreseinkommens gegenüber dem Status quo. Direkte modellierte Effekte, nicht das gesamte Parteiprogramm.</p></div><div className="flex gap-2"><button onClick={() => setIncome(40)} className={`rounded-xl px-4 py-3 text-sm font-bold ${income === 40 ? 'bg-ink text-white' : 'border border-border'}`}>40.000 € brutto</button><button onClick={() => setIncome(180)} className={`rounded-xl px-4 py-3 text-sm font-bold ${income === 180 ? 'bg-ink text-white' : 'border border-border'}`}>180.000 € brutto</button></div></div>
        <div className="mt-7 space-y-3">{rows.map((row) => <div key={row.party} className="grid grid-cols-[140px_1fr_92px] items-center gap-3"><div className="truncate text-sm font-bold">{row.party}</div><div className="relative h-8 overflow-hidden rounded-lg bg-bg-alt"><div className={`absolute top-0 h-full rounded-lg ${row.euro >= 0 ? 'left-1/2 bg-green/75' : 'right-1/2 bg-red/75'}`} style={{ width: `${Math.max(1, Math.abs(row.euro) / max * 50)}%` }} /><div className="absolute left-1/2 top-0 h-full w-px bg-ink/15" /></div><div className={`text-right text-sm font-black ${row.euro >= 0 ? 'text-green' : 'text-red'}`}>{money(row.euro)}</div></div>)}</div>
        <div className="mt-6 flex flex-wrap items-center gap-2 text-xs text-ink-muted"><span className="rounded-full bg-gold-light px-3 py-1 font-bold text-gold">echte veröffentlichte Mikrosimulation</span><span>{zewSource.model} · {zewSource.data}</span><a href={zewSource.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-bold underline underline-offset-4">Methodik <ExternalLink size={11} /></a></div>
      </section>

      <section className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-[2rem] bg-ink p-7 text-white"><div className="flex items-center gap-2 text-gold-light"><ArrowLeftRight size={18} /><span className="text-xs font-black uppercase tracking-widest">AfD Reality Check</span></div><h2 className="mt-4 text-3xl font-black">„Verarscht“? So würde FairEint es nicht formulieren.</h2><p className="mt-4 text-sm leading-relaxed text-white/70">Belegbar ist eine präzisere Aussage: In der ZEW-Simulation profitieren hohe Einkommen vom modellierten AfD-Steuer-/Transferpaket deutlich stärker als der Beispielhaushalt mit 40.000 € brutto.</p><div className="mt-6 space-y-3 text-sm"><Layer label="Was die Partei sagt" text={afdRealityCheck.claim} /><Layer label="Was das unabhängige Modell findet" text={afdRealityCheck.independentFinding} /><Layer label="Was dagegen eingewendet wird" text={afdRealityCheck.counterpoint} /></div></article>
        <article className="rounded-[2rem] border border-border bg-white p-7"><div className="text-xs font-black uppercase tracking-widest text-gold">Warum das wichtiger ist als ein Roast</div><h2 className="mt-3 text-3xl font-black">Der Nutzer darf selbst zum Schluss kommen.</h2><p className="mt-4 text-sm leading-relaxed text-ink-soft">FairEint sollte nicht sagen „Partei X betrügt dich“. Es sollte zeigen: <strong>Versprechen → modellierte Verteilungswirkung → Staatsfinanzen → Gegenargument → reale Abstimmungen.</strong> Das funktioniert genauso für SPD, Union, Grüne, Linke, FDP, BSW und AfD.</p><div className="mt-5 rounded-2xl bg-bg-alt p-4 text-sm"><strong>Beispiel:</strong> ZEW schätzt für die untersuchten AfD-Maßnahmen rund <strong>97 Mrd. € weniger staatliche Einnahmen</strong>. Ob das gut oder schlecht ist, hängt auch davon ab, welche Ausgaben gekürzt, welche anderen Einnahmen geschaffen oder welche Wachstumseffekte tatsächlich erreicht würden.</div></article></section>

      <section className="mt-10"><div className="flex items-center gap-2"><Scale /><h2 className="text-2xl font-black">Staatskasse und Verhaltensreaktionen</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-border bg-white p-5"><h3 className="font-black">Direkter fiskalischer Effekt</h3><div className="mt-4 space-y-3">{fiscalEvidence.map((item) => <div key={item.party} className="flex items-center justify-between gap-4 rounded-xl bg-bg-alt p-3"><span className="font-bold">{item.party}</span><span className="font-black text-red">{item.stateRevenueChangeBn} Mrd. €/Jahr</span></div>)}</div><p className="mt-4 text-xs leading-relaxed text-ink-muted">Nur untersuchte, modellierbare Programmbestandteile. Kein vollständiger Staatshaushalt.</p></div><div className="rounded-3xl border border-border bg-white p-5"><h3 className="font-black">Zweitrundeneffekte</h3><p className="mt-3 text-sm leading-relaxed text-ink-soft">{behaviourEvidence.finding}</p><p className="mt-3 text-xs leading-relaxed text-ink-muted">{behaviourEvidence.caveat}</p><a href={behaviourEvidence.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-bold underline underline-offset-4">ifo-Analyse öffnen <ExternalLink size={11} /></a></div></div></section>

      <section className="mt-10 rounded-[2rem] border border-border bg-white p-7 sm:p-9"><div className="flex items-start gap-3"><Vote className="mt-1 text-gold" /><div><div className="text-xs font-black uppercase tracking-widest text-gold">Bundestag Evidence Pipeline</div><h2 className="mt-2 text-2xl font-black">Was Parteien tatsächlich tun.</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-ink-soft">Der Bundestag stellt namentliche Abstimmungslisten maschinenlesbar bereit; das DIP bietet zusätzlich eine offizielle API für Parlamentsmaterialien. FairEint verlinkt diese Ground-Truth-Schicht jetzt direkt, behauptet aber noch keinen vollständigen lokalen Mirror.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><SourceLink href={bundestagData.rollCallsUrl} title="Namentliche Abstimmungen" detail="offizielle Abstimmungslisten" /><SourceLink href={bundestagData.openDataUrl} title="Bundestag Open Data" detail="XML, JSON, XLSX" /><SourceLink href={bundestagData.dipApiUrl} title="DIP API" detail="Vorgänge, Drucksachen, Positionen" /></div><div className="mt-5 rounded-2xl bg-gold-light p-4 text-xs leading-relaxed text-gold"><strong>Coverage:</strong> {bundestagData.coverage}</div></section>

      <section className="mt-10"><div className="flex items-center gap-2"><ShieldCheck /><h2 className="text-2xl font-black">Mehr Ground Truth, weniger politische Identität</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{groundTruth.map((item) => <a key={item.id} href={item.sourceUrl} target="_blank" rel="noreferrer" className="rounded-2xl border border-border bg-white p-4"><div className="text-3xl font-black">{item.value}{item.suffix}</div><div className="mt-2 text-sm font-bold">{item.label}</div><div className="mt-2 text-[11px] text-ink-muted">{item.fieldwork}</div></a>)}</div></section>

      <section className="mt-10 rounded-[2rem] bg-ink p-7 text-white sm:p-10"><div className="text-xs font-black uppercase tracking-widest text-gold-light">Policy Optimizer · nächster methodischer Schritt</div><h2 className="mt-3 text-3xl font-black">Nicht: „Welches Gesetz ist gut?“ Sondern: „Gut nach welchen Zielen?“</h2><p className="mt-4 max-w-3xl text-sm leading-relaxed text-white/65">Die seriöse Optimierung ist mehrkriteriell: verfügbare Einkommen, Armutsrisiko, Staatseinnahmen, Investitionen, Verwaltungsaufwand, Verhaltensreaktionen, Verfassungsrisiko und Bürgerpräferenzen. FairEint sollte für jede Option eine Pareto-Front zeigen statt einen geheimen Gesamtscore zu erfinden.</p><div className="mt-6 grid gap-3 md:grid-cols-3"><Metric title="1. Nutzen" text="Wer gewinnt wie viel – nach Einkommen, Haushalt, Region?" /><Metric title="2. Nebenwirkungen" text="Arbeitsangebot, Ausweichreaktionen, Liquidität, Bürokratie." /><Metric title="3. Demokratie" text="Repräsentative Präferenzen + reale politische Umsetzbarkeit." /></div></section>
    </section>
  </main>
}

function Layer({ label, text }: { label: string; text: string }) { return <div className="rounded-2xl bg-white/8 p-4"><div className="text-[11px] font-black uppercase tracking-widest text-white/40">{label}</div><p className="mt-2 leading-relaxed text-white/75">{text}</p></div> }
function SourceLink({ href, title, detail }: { href: string; title: string; detail: string }) { return <a href={href} target="_blank" rel="noreferrer" className="rounded-2xl border border-border p-4"><div className="flex items-center justify-between gap-2"><strong>{title}</strong><ExternalLink size={13} /></div><div className="mt-1 text-xs text-ink-muted">{detail}</div></a> }
function Metric({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl bg-white/8 p-4"><strong>{title}</strong><p className="mt-2 text-sm leading-relaxed text-white/60">{text}</p></div> }
