import { useMemo, useState } from 'react'
import { ArrowRight, Clock3, ExternalLink, Play, RotateCcw, Users } from 'lucide-react'
import PublicLabNav from './PublicLabNav'
import { workshop60, workshop120 } from './data/reality'

export default function WorkshopLab() {
  const [duration, setDuration] = useState<60 | 120>(60)
  const [active, setActive] = useState(0)
  const agenda = duration === 60 ? workshop60 : workshop120
  const elapsed = useMemo(() => agenda.slice(0, active).reduce((sum, item) => sum + item.minutes, 0), [agenda, active])
  const item = agenda[active]

  return <main className="min-h-screen bg-bg text-ink">
    <PublicLabNav active="workshop" />
    <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16">
      <div className="grid gap-8 lg:grid-cols-[1fr_360px]"><div><div className="text-xs font-black uppercase tracking-[0.18em] text-gold">Facilitator Mode · Bildung & Moderation</div><h1 className="mt-3 max-w-3xl text-4xl font-black leading-[1.02] tracking-[-0.04em] sm:text-6xl">Demokratie nicht nur erklären. <span className="text-gold">Erfahrbar machen.</span></h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-ink-soft">Ein moderierter Workshop rund um Bedürfnisse, politische Zielkonflikte, Evidenz und gemeinsame Lösungsräume. Parteipositionen kommen bewusst erst nach der eigenen Problemanalyse ins Spiel.</p><div className="mt-7 flex flex-wrap gap-2"><button onClick={() => { setDuration(60); setActive(0) }} className={`rounded-xl px-4 py-3 text-sm font-bold ${duration === 60 ? 'bg-ink text-white' : 'border border-border bg-white'}`}>60 Minuten</button><button onClick={() => { setDuration(120); setActive(0) }} className={`rounded-xl px-4 py-3 text-sm font-bold ${duration === 120 ? 'bg-ink text-white' : 'border border-border bg-white'}`}>120 Minuten</button></div></div>
        <aside className="rounded-3xl bg-ink p-6 text-white shadow-sm"><Users /><h2 className="mt-4 text-xl font-black">Für 6–24 Teilnehmende</h2><p className="mt-3 text-sm leading-relaxed text-white/70">Ideal in Paaren und Kleingruppen. Benötigt werden nur Smartphones oder Laptops und ein gemeinsamer Screen für Auswertung und Debrief.</p><div className="mt-5 border-t border-white/10 pt-5 text-xs leading-relaxed text-white/50">Kein offizielles HPI-Format. Der Ablauf ist von öffentlich beschriebenen Design-Thinking-Prinzipien inspiriert.</div><a href="https://hpi.de/d-school/themen/design-thinking/" target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-white/70 underline underline-offset-4">HPI Design Thinking <ExternalLink size={12} /></a></aside>
      </div>

      <section className="mt-10 grid gap-3 sm:grid-cols-3"><InfoCard title="1 · Bedürfnisse zuerst" text="Teilnehmende formulieren Probleme, bevor sie Parteien oder fertige Lösungen vergleichen." /><InfoCard title="2 · Evidenz sichtbar" text="Umfragen, Mikrosimulationen und Gegenpositionen werden als getrennte Evidenztypen behandelt." /><InfoCard title="3 · Konsens testen" text="Am Ende wird nicht nur Zustimmung gezählt, sondern nach gemeinsamen Prioritäten und verbleibenden Konflikten gesucht." /></section>

      <div className="mt-12 grid gap-7 lg:grid-cols-[300px_1fr]"><aside className="space-y-2">{agenda.map((step, index) => <button key={`${step.phase}-${index}`} onClick={() => setActive(index)} className={`w-full rounded-2xl border p-4 text-left transition ${active === index ? 'border-ink bg-ink text-white shadow-sm' : 'border-border bg-white hover:border-ink/20'}`}><div className={`text-[11px] font-black uppercase tracking-widest ${active === index ? 'text-white/45' : 'text-ink-muted'}`}>{step.minutes} min · Start bei Minute {elapsedFor(agenda, index)}</div><div className="mt-1 font-black">{index + 1}. {step.phase}</div></button>)}</aside>
        <section className="rounded-[2rem] border border-border bg-white p-7 shadow-sm sm:p-10"><div className="flex flex-wrap items-center justify-between gap-3"><div className="inline-flex items-center gap-2 rounded-full bg-bg-alt px-3 py-1.5 text-xs font-bold"><Clock3 size={14} /> Minute {elapsed}–{elapsed + item.minutes}</div><div className="text-xs font-bold text-ink-muted">Schritt {active + 1}/{agenda.length}</div></div><div className="mt-8 text-xs font-black uppercase tracking-[0.18em] text-gold">{item.phase}</div><h2 className="mt-3 text-3xl font-black leading-tight sm:text-4xl">{item.prompt}</h2>
          <div className="mt-8 grid gap-3 sm:grid-cols-3"><a href="./" className="rounded-2xl border border-border p-4 text-sm font-bold transition hover:border-ink/25 hover:bg-bg-alt">Policy Builder öffnen</a><a href="?reality=1" className="rounded-2xl border border-border p-4 text-sm font-bold transition hover:border-ink/25 hover:bg-bg-alt">Haushaltscheck öffnen</a><a href="./" className="rounded-2xl border border-border p-4 text-sm font-bold transition hover:border-ink/25 hover:bg-bg-alt">Haupttool öffnen → Konsens</a></div>
          <div className="mt-8 flex flex-wrap gap-2"><button disabled={active === 0} onClick={() => setActive(Math.max(0, active - 1))} className="rounded-xl border border-border px-4 py-3 text-sm font-bold disabled:opacity-30">Zurück</button><button onClick={() => setActive(active === agenda.length - 1 ? 0 : active + 1)} className="inline-flex items-center gap-2 rounded-xl bg-ink px-5 py-3 text-sm font-bold text-white">{active === agenda.length - 1 ? <><RotateCcw size={15} /> Neu starten</> : <><Play size={15} /> Nächste Phase <ArrowRight size={15} /></>}</button></div>
        </section></div>

      <section className="mt-12 rounded-[2rem] border border-border bg-white p-7 sm:p-10"><h2 className="text-2xl font-black">Debrief-Fragen für die Moderation</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-ink-muted">Die Reflexion sollte nicht darauf abzielen, eine „richtige“ politische Position zu erzeugen, sondern sichtbar zu machen, wie Bedürfnisse, Evidenz und Zielkonflikte Entscheidungen verändern.</p><div className="mt-5 grid gap-3 md:grid-cols-2"><Prompt text="Welche Entscheidung habt ihr zunächst aus politischer Identität getroffen – und welche aus konkreter Evidenz?" /><Prompt text="Wo wart ihr euch überraschend einig, obwohl eure politischen Ausgangspunkte unterschiedlich waren?" /><Prompt text="Welche Zahl hat eure Einschätzung verändert – und welche Zahl habt ihr angezweifelt?" /><Prompt text="Welche Nebenwirkung wäre für euch ein Grund, einen grundsätzlich guten Entwurf zu verändern?" /><Prompt text="Welche Gruppe oder Perspektive wurde in eurem ersten Entwurf übersehen?" /><Prompt text="Was müsste nach einem Jahr gemessen werden, um zu entscheiden, ob die Reform beibehalten oder angepasst wird?" /></div></section>
    </section>
  </main>
}

function elapsedFor(agenda: readonly { minutes: number }[], index: number) { return agenda.slice(0, index).reduce((sum, item) => sum + item.minutes, 0) }
function Prompt({ text }: { text: string }) { return <div className="rounded-2xl border border-border bg-bg p-4 text-sm font-semibold leading-relaxed">{text}</div> }
function InfoCard({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-border bg-white p-5"><strong>{title}</strong><p className="mt-2 text-sm leading-relaxed text-ink-muted">{text}</p></div> }
