import { useMemo, useState } from 'react'
import { ArrowRight, Clock3, ExternalLink, Play, RotateCcw, Users } from 'lucide-react'
import { workshop60, workshop120 } from './data/reality'

export default function WorkshopLab() {
  const [duration, setDuration] = useState<60 | 120>(60)
  const [active, setActive] = useState(0)
  const agenda = duration === 60 ? workshop60 : workshop120
  const elapsed = useMemo(() => agenda.slice(0, active).reduce((sum, item) => sum + item.minutes, 0), [agenda, active])
  const item = agenda[active]

  return <main className="min-h-screen bg-bg text-ink">
    <header className="border-b border-border bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-4 sm:px-6"><a href="./" className="font-black">FairEint</a><span className="rounded-full bg-ink px-2 py-1 text-[10px] font-black text-white">Workshop</span><a href="https://hpi.de/d-school/themen/design-thinking/" target="_blank" rel="noreferrer" className="ml-auto inline-flex items-center gap-1 text-xs font-bold text-ink-muted">HPI Design Thinking <ExternalLink size={12} /></a></div></header>

    <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><div><div className="text-xs font-black uppercase tracking-[0.18em] text-gold">Facilitator Mode</div><h1 className="mt-3 max-w-3xl text-5xl font-black leading-[0.98] tracking-[-0.04em]">Demokratie nicht erklären. <span className="text-gold">Erleben lassen.</span></h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-ink-soft">Ein Design-Thinking-Workshop rund um echte Bedürfnisse, politische Trade-offs, Evidenz und Konsens. Parteien kommen bewusst erst spät ins Spiel.</p><div className="mt-7 flex flex-wrap gap-2"><button onClick={() => { setDuration(60); setActive(0) }} className={`rounded-xl px-4 py-3 text-sm font-bold ${duration === 60 ? 'bg-ink text-white' : 'border border-border bg-white'}`}>60 Minuten</button><button onClick={() => { setDuration(120); setActive(0) }} className={`rounded-xl px-4 py-3 text-sm font-bold ${duration === 120 ? 'bg-ink text-white' : 'border border-border bg-white'}`}>120 Minuten</button></div></div><aside className="rounded-3xl bg-ink p-6 text-white"><Users /><h2 className="mt-4 text-xl font-black">Workshop-Prinzip</h2><p className="mt-3 text-sm leading-relaxed text-white/65">Erst Bedürfnisse verstehen. Dann individuell entscheiden. Erst danach Daten, Parteien und Gruppenkonsens sichtbar machen. So reduziert der Ablauf Lagerdenken und erhöht Reflexion.</p><div className="mt-5 text-xs text-white/50">Kein offizielles HPI-Format. FairEint orientiert sich an den veröffentlichten sechs HPI Design-Thinking-Phasen.</div></aside></div>

      <div className="mt-12 grid gap-7 lg:grid-cols-[300px_1fr]"><aside className="space-y-2">{agenda.map((step, index) => <button key={`${step.phase}-${index}`} onClick={() => setActive(index)} className={`w-full rounded-2xl border p-4 text-left ${active === index ? 'border-ink bg-ink text-white' : 'border-border bg-white'}`}><div className={`text-[11px] font-black uppercase tracking-widest ${active === index ? 'text-white/45' : 'text-ink-muted'}`}>{step.minutes} min · {elapsedFor(agenda, index)} min Start</div><div className="mt-1 font-black">{index + 1}. {step.phase}</div></button>)}</aside>
        <section className="rounded-[2rem] border border-border bg-white p-7 shadow-sm sm:p-10"><div className="flex flex-wrap items-center justify-between gap-3"><div className="inline-flex items-center gap-2 rounded-full bg-bg-alt px-3 py-1.5 text-xs font-bold"><Clock3 size={14} /> Minute {elapsed}–{elapsed + item.minutes}</div><div className="text-xs font-bold text-ink-muted">Schritt {active + 1}/{agenda.length}</div></div><div className="mt-8 text-xs font-black uppercase tracking-[0.18em] text-gold">{item.phase}</div><h2 className="mt-3 text-3xl font-black leading-tight sm:text-4xl">{item.prompt}</h2>
          <div className="mt-8 grid gap-3 sm:grid-cols-3"><a href="./" className="rounded-2xl border border-border p-4 font-bold">Policy Builder öffnen</a><a href="?reality=1" className="rounded-2xl border border-border p-4 font-bold">Reality Check öffnen</a><a href="./" className="rounded-2xl border border-border p-4 font-bold">Konsens-Lab im Haupttool</a></div>
          <div className="mt-8 flex flex-wrap gap-2"><button disabled={active === 0} onClick={() => setActive(Math.max(0, active - 1))} className="rounded-xl border border-border px-4 py-3 text-sm font-bold disabled:opacity-30">Zurück</button><button onClick={() => setActive(active === agenda.length - 1 ? 0 : active + 1)} className="inline-flex items-center gap-2 rounded-xl bg-ink px-5 py-3 text-sm font-bold text-white">{active === agenda.length - 1 ? <><RotateCcw size={15} /> Nochmal</> : <><Play size={15} /> Nächste Phase <ArrowRight size={15} /></>}</button></div>
        </section></div>

      <section className="mt-12 rounded-[2rem] bg-white p-7 sm:p-10"><h2 className="text-2xl font-black">Debrief-Fragen für den Educator</h2><div className="mt-5 grid gap-3 md:grid-cols-2"><Prompt text="Welche Entscheidung habt ihr aus Identität getroffen – und welche aus Evidenz?" /><Prompt text="Wo wart ihr euch überraschend einig, obwohl ihr politisch unterschiedlich denkt?" /><Prompt text="Welche Zahl hat eure Meinung verändert – und welche Zahl habt ihr angezweifelt?" /><Prompt text="Welche Nebenwirkung wäre für euch ein Grund, ein eigentlich gutes Gesetz zu ändern?" /><Prompt text="Welche Gruppe wurde in eurem ersten Entwurf vergessen?" /><Prompt text="Was müsste gemessen werden, damit ihr das Gesetz nach einem Jahr beibehalten würdet?" /></div></section>
    </section>
  </main>
}

function elapsedFor(agenda: readonly { minutes: number }[], index: number) { return agenda.slice(0, index).reduce((sum, item) => sum + item.minutes, 0) }
function Prompt({ text }: { text: string }) { return <div className="rounded-2xl border border-border bg-bg p-4 text-sm font-semibold leading-relaxed">{text}</div> }
